name: Deploy Ginong-Sout to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # 리포지토리 코드 checkout
    - name: Checkout
      uses: actions/checkout@v3

    # SSH 접속 및 배포.sh 실행
    - name: SSH Connection for Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/sout/dev/repositories
          ./deploy.sh
